name: Release latest tag

on:
  create:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build and release distros
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To use `git describe --tags`

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Setup Task
        uses: arduino/setup-task@v2

      - name: Build and package
        run: task build-all

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            result/*.tar.gz